### ISSUE TITLE
No enum constant net.runelite.client.config.FlashNotification.true

### ISSUE THREAD

**Issue by IanWONeill** [runelite-extended/runelite#1062]
java.lang.IllegalArgumentException: No enum constant net.runelite.client.config.FlashNotification.true
	at java.lang.Enum.valueOf(Enum.java:238)
	at net.runelite.client.config.ConfigManager.stringToObject(ConfigManager.java:506)
	at net.runelite.client.config.ConfigInvocationHandler.lambda$invoke$0(ConfigInvocationHandler.java:111)
	at java.util.HashMap.computeIfAbsent(HashMap.java:1127)
	at net.runelite.client.config.ConfigManager.getConfigObjectFromCacheOrElse(ConfigManager.java:228)
	at net.runelite.client.config.ConfigInvocationHandler.invoke(ConfigInvocationHandler.java:92)
	at com.sun.proxy.$Proxy23.flashNotification(Unknown Source)
	at net.runelite.client.Notifier.notify(Notifier.java:153)
	at net.runelite.client.Notifier.notify(Notifier.java:114)

**Comment by Kyleeld** [comment]
DISABLED("Off"),
	FLASH_TWO_SECONDS("Flash for 2 seconds"),
	SOLID_TWO_SECONDS("Solid for 2 seconds"),
	FLASH_UNTIL_CANCELLED("Flash until cancelled"),
	SOLID_UNTIL_CANCELLED("Solid until cancelled");

there is no FlashNotification True - try rebuilding :)
