### ISSUE TITLE
GPU Plugin: ERROR net.runelite.client.RuneLite - Game crash: null

### ISSUE THREAD

**Issue by IanWONeill** [runelite-extended/runelite#1073]
2019-07-21 04:59:00 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: GL-Error 0x505 while creating mutable storage for target 0x8892 -> buffer 5 of size 0 with data java.nio.DirectIntBufferU[pos=0 lim=0 cap=16777216]
	at jogamp.opengl.GLBufferObjectTracker.createBufferStorage(GLBufferObjectTracker.java:176)
	at jogamp.opengl.gl4.GL4bcImpl.glBufferData(GL4bcImpl.java:40258)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:911)
	at bz.onPost(bz.java:86)
	at bz.p(bz.java)
	at bz.run(bz.java:345)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Kyleeld** [comment]
this happens on normal rl also.
