### ISSUE TITLE
slayer: task kill count does not go down 

### ISSUE THREAD

**Issue by Sithari98** [runelite-extended/runelite#1110]
Will reappear correct when checking gem but does not go down as you complete the task. Problem on 07 and and world 45 dmm.

**Comment by xperiaclash** [comment]
2019-07-24 19:43:12 [Client] ERROR n.runelite.client.eventbus.EventBus - java.lang.NullPointerException
	at net.runelite.client.plugins.slayer.SlayerPlugin.onExperienceChanged(SlayerPlugin.java:738)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
	at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
	at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:72)
	at net.runelite.client.callback.Hooks.post(Hooks.java:133)
	at client.experiencedChanged(client.java:1009)
	at client.gg(client.java:6021)
	at client.fg(client.java:2412)
	at client.ad(client.java:921)
	at bz.j(bz.java:364)
	at bz.run(bz.java:343)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Kyleeld** [comment]
fixed in #1133
