### ISSUE TITLE
Grand Exchange Plugin: java.lang.NullPointerException

### ISSUE THREAD

**Issue by JourneyOver** [runelite-extended/runelite#1161]
**Describe the bug**

Opening grand exchange and opening a buy offer on an item throws an error and no longer shows:
```
OSB actively traded prices
GE limits
Afford quantity
```

The error in question:
```
2019-07-27 04:32:30 [Client] ERROR n.runelite.client.eventbus.EventBus - Error in eventbus: null
2019-07-27 04:32:30 [Client] ERROR n.runelite.client.eventbus.EventBus - java.lang.NullPointerException
    at java.util.Objects.requireNonNull(Objects.java:203)
    at net.runelite.client.plugins.grandexchange.GrandExchangePlugin.onGameTick(GrandExchangePlugin.java:547)
    at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
    at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
    at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
    at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
    at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
    at net.runelite.client.eventbus.EventBus.post(EventBus.java:72)
    at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:151)
    at client.draw(client.java:1426)
    at client.ag(client.java)
    at bz.s(bz.java:390)
    at bz.run(bz.java:344)
    at java.lang.Thread.run(Thread.java:748)
```

**To Reproduce**
1. Have GE plugin enabled with it's options
2. Open a buy offer in the grand exchange for a random item
3. Notice that none of the options seem to be working
4. Open logs and notice the error above.

**Expected behavior**

For OSB actively traded prices, GE limits, and afford quantity to show when buying something

**Screenshots**

![java_07-27-2019_18-47-53](https://user-images.githubusercontent.com/13910285/62000552-1af40880-b09f-11e9-8c39-f0e1a5f32230.png)

**Environment (please complete the following information):**
 - OS: Windows 10 x64 bit
 - RuneLite version: 1.5.30-snapshot
 - Launcher version: 2.1.0.0

**Additional context**

I've had this in both my dev build (which is using a slightly older version of the grand exchange plugin to fix afford quantity until #1061 is fixed) and in the master branch (and launching through the launcher)

You can see the diffs for the errors here https://www.diffchecker.com/cutYv3N5 (mine on the left, launcher/master on the right (which is the same as the above error in the `Describe the bug` section)) but they both seem to lead to the same thing.

Seems a temporary fix to this issue is to sell an item, collect the coins and then open a buy offer on an item. Sometimes this temporary fix only seems to works when being done on the launcher and sometimes it only works from dev build but once the temp fix has been done it seems to span all variants (launcher and dev builds), though it does seem to go away eventually which is why I call this a temporary fix.

Should make note that this does not happen in normal runelite, only seems to be runelite+

**Comment by pklite** [comment]
fixed in #1583
