### ISSUE TITLE
runescape-client Crash on start

### ISSUE THREAD

**Issue by LandyLane** [runelite-extended/runelite#1210]
**Describe the bug**
Upon starting the runescape-client there is a error_game_crash caused by a NegativeArraySizeException. 
`java.lang.NegativeArraySizeException
error_game_crash
	at BZip2Decompressor.BZip2Decompressor_decompress(BZip2Decompressor.java:197)
	at BZip2Decompressor.BZip2Decompressor_decompress(BZip2Decompressor.java:33)
	at HealthBarUpdate.decompressBytes(HealthBarUpdate.java:224)
	at Archive.load(Archive.java:242)
	at SecureRandomFuture.method2056(SecureRandomFuture.java:91)
	at Archive.loadIndex(Archive.java:164)
	at WorldMapArea.method365(WorldMapArea.java:620)
	at Client.doCycleJs5(Client.java:2026)
	at Client.doCycle(Client.java:1620)
	at GameShell.method953(GameShell.java:593)
	at GameShell.run(GameShell.java:920)
	at java.lang.Thread.run(Thread.java:748)
`

**To Reproduce**
1. Download package
2. Add a OSRSLoader class to load the client
3. Error is thrown during red bar indicating its updating cache.

**Environment (please complete the following information):**
 - OS: Windows 10 64 bit
 - Java Version: JDK1.8.0_161 in Eclipse

**Additional context**
Saw there is a ':( git' message on the BZip classes, not sure if this is expected.

**Comment by LandyLane** [comment]
In BZip2Decompressor changing var0.blockSize100k from 1410065408 to 1 loads the client but is still very buggy.

**Comment by Lucwousin** [comment]
You know there's no real reason to run runescape client except for finding out what things are/playing a rsps?

Deob had a hiccup there. The name of that field kinda gives it away btw, it's supposed to be 100000

**Comment by Lucwousin** [comment]
wait no it isnt im retarded
