### ISSUE TITLE
freezetimers: ConcurrentModificationException

### ISSUE THREAD

**Issue by Ganom** [runelite-extended/runelite#1305]
```java
2019-08-11 13:47:33 [Client] ERROR n.runelite.client.eventbus.EventBus - Error in eventbus: null
2019-08-11 13:47:33 [Client] ERROR n.runelite.client.eventbus.EventBus - java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$KeyIterator.next(Unknown Source)
	at net.runelite.client.plugins.freezetimers.Timers.getAllActorsOnTimer(Timers.java:84)
	at net.runelite.client.plugins.freezetimers.FreezeTimersPlugin.onGameTick(FreezeTimersPlugin.java:182)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
	at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
	at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:81)
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:152)
	at client.draw(client.java:1426)
	at client.ag(client.java)
	at bz.s(bz.java:390)
	at bz.run(bz.java:344)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by se7enAte9** [comment]
For anyone who wants to fix:

This error will happen when an element is removed from `timerMap` on [#L111](https://github.com/runelite-extended/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/Timers.java#L111) in `areAllTimersZero` at [#L86](https://github.com/runelite-extended/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/Timers.java#L86). The removal is occuring while `timerMap.keySet()` is being iterated with a `for each` loop on [#L84](https://github.com/runelite-extended/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/freezetimers/Timers.java#L84) which results in a `ConcurrentModificationException`. The easiest solution would probably be to loop through a copy of `timerMap.keySet()` or use an `Iterator` instead of a `for each` loop.

**Comment by Ganom** [comment]
Closed by 1349
