### ISSUE TITLE
403 on opening launcher

### ISSUE THREAD

**Issue by stevebasher** [runelite-extended/runelite#1364]
I'm unable to launch RuneLitePlus.jar. Taking a look at `launcher.log` it seems I hit a 403 when trying to download the new client:

```
2019-08-16 13:21:31 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.io.IOException: Server returned HTTP response code: 403 for URL: https://nexus.runelitepl.us/repository/runelite/net/runelite/client/1.5.32-SNAPSHOT/client-1.5.32-20190816.002611-1.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1894)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at net.runelite.launcher.Launcher.download(Launcher.java:321)
	at net.runelite.launcher.Launcher.main(Launcher.java:182)
```

A quick re-download of the .jar didn't solve the issue.

**Comment by stevebasher** [comment]
Issue also occurs when using the Native MacOS app

**Comment by stevebasher** [comment]
Nevermind, seems your artifact address is being blocked by my DNS filter all of a sudden
