### ISSUE TITLE
FileNotFound on opening launcher

### ISSUE THREAD

**Issue by 4ilo** [runelite-extended/runelite#1374]
Opening the launcher results in the following error:
```
2019-08-17 09:01:27 [main] ERROR net.runelite.launcher.Launcher - unable to download artifacts
java.io.FileNotFoundException: https://nexus.runelitepl.us/repository/runelite/net/runelite/http-api/1.5.32-SNAPSHOT/http-api-1.5.32-20190816.002611-1.jar
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1890)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at net.runelite.launcher.Launcher.download(Launcher.java:330)
	at net.runelite.launcher.Launcher.main(Launcher.java:187)
```

**Comment by Owain94** [comment]
I'm currently waiting on one other dev to approve the next live update, that will fix this issue, should be fixed in 10-30 minutes. Sorry for the inconvenience.
