### ISSUE TITLE
examineplugin/chatcommands: failing to get info

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#1384]
Price command:
```java
2019-08-18 13:52:22 [Client] DEBUG net.runelite.client.RuneLite - Chat message type ITEM_EXAMINE: A vicious, curved sword.
2019-08-18 13:52:22 [Client] DEBUG n.r.c.plugins.examine.ExaminePlugin - Got examine for ITEM 1333: A vicious, curved sword.
2019-08-18 13:52:22 [pool-2-thread-1] DEBUG n.r.h.a.o.OSBGrandExchangeClient - Built URI: https://api.runelite.net/runelite-1.5.31.1/osb/ge?itemId=1333
2019-08-18 13:52:22 [Client] ERROR n.r.c.plugins.examine.ExaminePlugin - java.io.IOException: Error looking up item id: Response{protocol=http/1.1, code=403, message=Forbidden, url=https://api.runelite.net/runelite-1.5.31.1/osb/ge?itemId=1333}

```
!task command
```java
2019-08-18 15:10:47 [Client] DEBUG net.runelite.client.RuneLite - Chat message type FRIENDSCHAT: !Task
2019-08-18 15:10:47 [pool-2-thread-1] DEBUG n.r.c.plugins.slayer.SlayerPlugin - unable to lookup slayer task
java.io.IOException: Unable to look up task!
	at net.runelite.http.api.chat.ChatClient.getTask(ChatClient.java:173)
	at net.runelite.client.plugins.slayer.SlayerPlugin.taskLookup(SlayerPlugin.java:1151)
	at net.runelite.client.chat.ChatCommandManager.lambda$onChatMessage$0(ChatCommandManager.java:122)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Running current github build, latest pull when this issue was created

**Comment by justingerolami** [comment]
!kc also bugged

**Comment by SRLJustin** [comment]
this is now resolved - http-api must've been offline/in an error state, closing
