### ISSUE TITLE
clanchat: UnsupportedOperationException

### ISSUE THREAD

**Issue by Ganom** [runelite-extended/runelite#1407]
```java
2019-08-10 21:28:22 [Client] ERROR n.runelite.client.eventbus.EventBus - java.lang.UnsupportedOperationException
	at java.util.concurrent.CopyOnWriteArrayList$COWIterator.remove(CopyOnWriteArrayList.java:1178)
	at net.runelite.client.plugins.clanchat.ClanChatPlugin.onClanMemberLeft(ClanChatPlugin.java:268)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
	at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
	at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:81)
	at net.runelite.client.util.DeferredEventBus.replay(DeferredEventBus.java:64)
	at net.runelite.client.callback.Hooks.updateNpcs(Hooks.java:465)
	at client.updateNpcs(client.java:1399)
	at bh.gv(bh.java)
	at client.gg(client.java:6475)
	at client.fg(client.java:2412)
	at client.ad(client.java:921)
	at bz.j(bz.java:364)
	at bz.run(bz.java:343)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by se7enAte9** [comment]
As the [API](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CopyOnWriteArrayList.html) states, calling any element-changing operation on a `CopyOnWriteArrayList` will result in an `UnsupportedOperationException`. In this case a `for-each` loop should work instead of an `iterator`.
