### ISSUE TITLE
MES randomly stops functioning until client is restarted

### ISSUE THREAD

**Issue by Jawnb64** [runelite-extended/runelite#1410]
**Describe the bug**
MES plugin acts as if it were disabled entirely

**To Reproduce**
Unknown

**Logs** 
[client_2019-08-20.0.log](https://github.com/runelite-extended/runelite/files/3522618/client_2019-08-20.0.log)
[client_2019-08-20.1.log](https://github.com/runelite-extended/runelite/files/3522619/client_2019-08-20.1.log)
[client_2019-08-20.2.log](https://github.com/runelite-extended/runelite/files/3522620/client_2019-08-20.2.log)
[client_2019-08-20.3.log](https://github.com/runelite-extended/runelite/files/3522614/client_2019-08-20.3.log)
[client_2019-08-20.4.log](https://github.com/runelite-extended/runelite/files/3522615/client_2019-08-20.4.log)
[client_2019-08-20.5.log](https://github.com/runelite-extended/runelite/files/3522616/client_2019-08-20.5.log)
[client_2019-08-20.6.log](https://github.com/runelite-extended/runelite/files/3522617/client_2019-08-20.6.log)
[client_2019-08-20.7.log](https://github.com/runelite-extended/runelite/files/3522608/client_2019-08-20.7.log)
[client_2019-08-20.8.log](https://github.com/runelite-extended/runelite/files/3522609/client_2019-08-20.8.log)

[client_2019-08-20.9.log](https://github.com/runelite-extended/runelite/files/3522626/client_2019-08-20.9.log)

edit - thatgamerblue:
from lordzuku in #1415:
```txt
a few hours before it happened, noticed an oob error with the menu entrys
https://pastebin.com/vpjinKSW

then this was the logs at the time when the all menu entrys broke
https://pastebin.com/gmGbE5w6
```

**Comment by se7enAte9** [comment]
I looked through the first and last log, both of which were filled with close to 200,000 lines of the following error. I'm going to assume the other 8 logs are also filled with the same error. I'm not sure how this `NullPointerException` relates to MES, but here it is for anyone who wants to looks at it.

`2019-08-20 16:45:35 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at net.runelite.client.plugins.multiindicators.MultiIndicatorsMinimapOverlay.render(MultiIndicatorsMinimapOverlay.java:117)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:526)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:278)
	at net.runelite.client.callback.Hooks.draw(Hooks.java:325)
	at bp.p(bp.java:63)
	at bp.w(bp.java:39)
	at client.ag(client.java:1002)
	at bz.s(bz.java:390)
	at bz.run(bz.java:344)
	at java.lang.Thread.run(Unknown Source)`

**Comment by Colpo1** [comment]
Same issue:

`2019-08-24 11:57:04 [Client] ERROR n.runelite.client.eventbus.EventBus - Error in eventbus: start 12, end 3, s.length() 3
2019-08-24 11:57:04 [Client] ERROR n.runelite.client.eventbus.EventBus - java.lang.IndexOutOfBoundsException: start 12, end 3, s.length() 3
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:539)
	at java.lang.StringBuffer.append(StringBuffer.java:350)
	at java.util.regex.Matcher.appendTail(Matcher.java:911)
	at java.util.regex.Matcher.replaceAll(Matcher.java:958)
	at net.runelite.client.util.Text.removeTags(Text.java:82)
	at net.runelite.client.util.Text.standardize(Text.java:93)
	at net.runelite.client.plugins.menuentryswapper.MenuEntrySwapperPlugin.onMenuEntryAdded(MenuEntrySwapperPlugin.java:501)
	at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.internal.operators.observable.ObservableMap$MapObserver.onNext(ObservableMap.java:62)
	at io.reactivex.internal.operators.observable.ObservableFilter$FilterObserver.onNext(ObservableFilter.java:52)
	at com.jakewharton.rxrelay2.PublishRelay$PublishDisposable.onNext(PublishRelay.java:180)
	at com.jakewharton.rxrelay2.PublishRelay.accept(PublishRelay.java:145)
	at com.jakewharton.rxrelay2.SerializedRelay.accept(SerializedRelay.java:57)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:81)
	at net.runelite.client.callback.Hooks.post(Hooks.java:159)
	at client.onMenuOptionsChanged(client.java:734)
	at eo.hn(eo.java:8745)
	at gp.hi(gp.java:8732)
	at ap.io(ap.java:9986)
	at e.ij(p.java:10200)
	at hz.iz(hz.java:10067)
	at e.ij(p.java:10519)
	at e.ij(p.java:10500)
	at e.ij(p.java:10500)
	at hz.iz(hz.java:10067)
	at client.fg(client.java:2717)
	at client.ad(client.java:921)
	at bz.j(bz.java:364)
	at bz.run(bz.java:343)
	at java.lang.Thread.run(Thread.java:748)`
