### ISSUE TITLE
Invalid enum config values throw a exception

### ISSUE THREAD

**Issue by Lucwousin** [runelite-extended/runelite#1518]
Invalid config values (for enums) still error out, and don't reset to default configuration after a miss.

duplicate of #1062 which was closed too soon. I remember doing something to fix this way back but seems like it has been un-unfixed

```2019-09-02 15:37:38 [RuneLite] WARN  n.r.client.config.ConfigManager - Unable to unmarshal runelite.notificationFlash
java.lang.IllegalArgumentException: No enum constant net.runelite.client.config.FlashNotification.false
    at java.base/java.lang.Enum.valueOf(Unknown Source)
    at net.runelite.client.config.ConfigManager.stringToObject(ConfigManager.java:511)
    at net.runelite.client.config.ConfigManager.getConfiguration(ConfigManager.java:275)
    at net.runelite.client.config.ConfigManager.setDefaultConfiguration(ConfigManager.java:437)
    at net.runelite.client.plugins.PluginManager.loadDefaultPluginConfiguration(PluginManager.java:209)
    at net.runelite.client.RuneLite.start(RuneLite.java:324)
    at net.runelite.client.RuneLite.main(RuneLite.java:284)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at net.runelite.launcher.ReflectionLauncher$1.run(ReflectionLauncher.java:64)```

**Comment by Lucwousin** [comment]
#455 was what fixed this before
