### ISSUE TITLE
Barbarian Assault egg item names

### ISSUE THREAD

**Issue by Errors4l** [runelite-extended/runelite#1666]
**Describe the bug**
Eggs for collector show incorrect names in Barbarian Assault and can sometimes not be picked up. Remove unused menus also seems to be broken.

**To Reproduce**
1. (Remove unused menus = checked.)
2. Play collector in BA.
3. Wait for eggs to drop

**Expected behavior**
Eggs are highlighted and you can only pick up the eggs called out to you. Item names aren't messed up as seen in the screenshot.

**Screenshots**
![](https://i.imgur.com/m56XpEo.png)

**Environment (please complete the following information):**
- OS: Windows 10
- RuneLite version: 1.5.35-SNAPSHOT
- RuneLitePlus version: 2.1.6.0
- Launcher version: .. Latest..?

**Additional context**
<details>

```
2019-09-27 03:29:49 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-09-27 03:29:50 [RuneLite] INFO  n.r.client.plugins.PluginManager - Plugin instantiation took 761ms
2019-09-27 03:29:53 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-09-27 03:29:54 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 5695ms. Uptime: 13777ms
2019-09-27 03:29:54 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLitePlus,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1071x701,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@7c3c18b8,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-09-27 03:29:55 [pool-3-thread-1] INFO  n.r.c.p.l.LootTrackerPlugin - Loaded 2973 locally stored loot records
2019-09-27 03:34:08 [Preloader] INFO  net.runelite.client.rs.ClientLoader - client-patch 304703841.269
2019-09-27 03:34:08 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-09-27 03:34:09 [RuneLite] INFO  n.r.c.plugins.kourendlibrary.Library - Library is now reset
2019-09-27 03:34:10 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-09-27 03:34:12 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 7019ms. Uptime: 21115ms
2019-09-27 03:34:12 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLite,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1071x701,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@5926fe94,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-09-27 03:53:42 [pool-3-thread-1] INFO  n.r.c.p.c.ChatCommandsPlugin - gc lookup
2019-09-27 03:57:48 [pool-3-thread-1] INFO  n.r.c.p.c.ChatCommandsPlugin - gc lookup
2019-09-27 03:57:54 [pool-3-thread-1] INFO  n.r.c.p.c.ChatCommandsPlugin - gc lookup
2019-09-27 03:58:10 [pool-3-thread-1] INFO  n.r.c.p.c.ChatCommandsPlugin - gc lookup
2019-09-27 03:58:20 [pool-3-thread-1] INFO  n.r.c.p.c.ChatCommandsPlugin - gc lookup
2019-09-27 03:58:48 [pool-3-thread-1] INFO  n.r.c.p.c.ChatCommandsPlugin - gc lookup
2019-09-27 04:25:43 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-09-27 04:25:45 [RuneLite] INFO  n.r.client.plugins.PluginManager - Plugin instantiation took 986ms
2019-09-27 04:25:49 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-09-27 04:25:49 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6888ms. Uptime: 9623ms
2019-09-27 04:25:49 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLitePlus,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1071x701,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@9705b49,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-09-27 04:25:52 [pool-3-thread-1] INFO  n.r.c.p.l.LootTrackerPlugin - Loaded 2973 locally stored loot records
2019-09-27 04:25:54 [Client] WARN  n.r.client.plugins.gpu.GpuPlugin - Canvas invalidated!
2019-09-27 04:25:58 [Client] ERROR net.runelite.client.RuneLite - Game crash: null
com.jogamp.opengl.GLException: Error swapping buffers
	at jogamp.opengl.windows.wgl.WindowsWGLDrawable.swapBuffersImpl(WindowsWGLDrawable.java:93)
	at jogamp.opengl.GLDrawableImpl.swapBuffers(GLDrawableImpl.java:88)
	at net.runelite.client.plugins.gpu.GpuPlugin.draw(GpuPlugin.java:1197)
	at bh.onPost(bh.java:86)
	at bh.r(bh.java)
	at bh.run(bh.java:335)
	at java.base/java.lang.Thread.run(Unknown Source)
2019-09-27 04:30:50 [RuneLite] INFO  n.r.client.account.SessionManager - No session file exists
2019-09-27 04:30:51 [RuneLite] INFO  n.r.client.plugins.PluginManager - Plugin instantiation took 848ms
2019-09-27 04:30:54 [RuneLite] INFO  n.r.client.discord.DiscordService - Initializing Discord RPC service.
2019-09-27 04:30:54 [RuneLite] INFO  net.runelite.client.RuneLite - Client initialization took 6190ms. Uptime: 9184ms
2019-09-27 04:30:55 [AWT-EventQueue-0] INFO  net.runelite.client.ui.ClientUI - Showing frame net.runelite.client.ui.ContainableFrame[frame0,0,0,1920x1040,layout=java.awt.BorderLayout,title=RuneLitePlus,resizable,maximized,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=javax.swing.JRootPane[,0,0,1071x701,layout=org.pushingpixels.substance.internal.ui.SubstanceRootPaneUI$SubstanceRootLayout,alignmentX=0.0,alignmentY=0.0,border=org.pushingpixels.substance.internal.utils.border.SubstancePaneBorder@71e520ef,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
2019-09-27 04:30:57 [Client] WARN  n.r.client.plugins.gpu.GpuPlugin - Canvas invalidated!
2019-09-27 04:30:59 [pool-3-thread-1] INFO  n.r.c.p.l.LootTrackerPlugin - Loaded 2973 locally stored loot records
```

</details

**Comment by Errors4l** [comment]
Issue seems to have resolved itself in one of the recent updates.
