### ISSUE TITLE
Screen markers is broken

### ISSUE THREAD

**Issue by renewablezip01** [runelite-extended/runelite#181]
When adding a screen marker, the client bugs out and makes the screen marker tab look empty like so: http://prntscr.com/nkec7e

So i ran the client through cmd to check the issue and thats what i got
`2019-05-04 20:10:15 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.ExceptionInInitializerError: null
        at net.runelite.client.plugins.screenmarkers.ui.ScreenMarkerPluginPanel.init(ScreenMarkerPluginPanel.java:116)
        at net.runelite.client.plugins.screenmarkers.ui.ScreenMarkerPluginPanel.rebuild(ScreenMarkerPluginPanel.java:174)
        at net.runelite.client.plugins.screenmarkers.ScreenMarkerPlugin.finishCreation(ScreenMarkerPlugin.java:191)
        at net.runelite.client.plugins.screenmarkers.ui.ScreenMarkerCreationPanel$1.mousePressed(ScreenMarkerCreationPanel.java:88)
        at java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: input == null!
        at javax.imageio.ImageIO.read(Unknown Source)
        at net.runelite.client.util.ImageUtil.getResourceStreamFromClass(ImageUtil.java:354)
        at net.runelite.client.plugins.screenmarkers.ui.ScreenMarkerPanel.<clinit>(ScreenMarkerPanel.java:142)
        ... 36 common frames omitted`

the screen marker tab should look like this: http://prntscr.com/nkee11

/Xelian

**Comment by Ganom** [comment]
That error typically indicates a image is missing from resource folder, i'll take a look in a minute.

**Comment by Ganom** [comment]
Fixed in https://github.com/runelite-extended/runelite/pull/182
