### ISSUE TITLE
Noted items have no value on examine.

### ISSUE THREAD

**Issue by Ganom** [runelite-extended/runelite#340]
**Describe the bug**
Noted items have no value on examine.

**To Reproduce**
Examine a noted item.

**Expected behavior**
Noted item should grab value from osb ge feed.

**Screenshots**
![image](https://user-images.githubusercontent.com/8338284/58067712-5a145380-7b5c-11e9-9ecb-992b20f50037.png)

**Comment by Ganom** [comment]
```
2019-05-21 00:05:10 [pool-2-thread-1] WARN  n.r.c.util.RunnableExceptionLogger - Uncaught exception in runnable net.runelite.client.plugins.examine.ExaminePlugin$$Lambda$1173/655963347@2102dd21
java.lang.NullPointerException: null
	at net.runelite.client.plugins.examine.ExaminePlugin.getItemPrice(ExaminePlugin.java:366)
	at net.runelite.client.plugins.examine.ExaminePlugin.lambda$onChatMessage$0(ExaminePlugin.java:213)
	at net.runelite.client.util.RunnableExceptionLogger.run(RunnableExceptionLogger.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Stack Trace
