### ISSUE TITLE
Freeze timers plugin

### ISSUE THREAD

**Issue by renewablezip01** [runelite-extended/runelite#44]
Currently the plugin stops working after casting a spell that freeze the opponent, i spell i was testing was bind, snare and entangle. This is what i got in the cmd

`n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.IllegalStateException: No match found
	at java.util.regex.Matcher.group(Matcher.java:536)
	at net.runelite.client.plugins.freezetimers.FreezeTimersPlugin.onMenuOptionClicked(FreezeTimersPlugin.java:134)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)
	at net.runelite.client.callback.Hooks.post(Hooks.java:134)
	at aq.iu(aq.java:1290)
	at bd.ie(bd.java:8094)
	at client.iy(client.java:8035)
	at client.fu(client.java:3119)
	at client.av(client.java:1000)
	at bf.aa(bf.java:359)
	at bf.run(bf.java:338)
	at java.lang.Thread.run(Thread.java:748)`
which caused it to stop working

**Comment by sdburns1998** [comment]
Can you try with https://github.com/runelite-extended/runelite/pull/45?
