### ISSUE TITLE
Zulrah Plugin is no longer working.

### ISSUE THREAD

**Issue by ILLuMiNaTe7** [runelite-extended/runelite#585]
**Describe the bug**
The plugin no longer works when engaging Zulrah.

**To Reproduce**
1. Enter the rowboat.
2. Watch Cutscene
3. See error

**Expected behavior**
Prayer helper and marked tiles on the screen.

**Additional context**
Logs:
```
2019-06-13 12:09:08 [Client] DEBUG n.r.c.p.g.GroundMarkerPlugin - Loading points for region 9007  
2019-06-13 12:09:08 [Client] DEBUG n.r.c.p.g.GroundMarkerPlugin - Loading points for region 9008  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.plugins.zulrah.ZulrahPlugin - Zulrah encounter has started.  
2019-06-13 12:09:15 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber  
java.lang.NullPointerException: null  
	at net.runelite.client.plugins.zulrah.ZulrahPlugin.onGameTick(ZulrahPlugin.java:170)  
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)  
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)  
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:155)  
	at client.methodDraw(client.java:1340)  
	at client.ab(client.java)  
	at ba.ar(ba.java:419)  
	at ba.run(ba.java:373)  
	at java.lang.Thread.run(Unknown Source)  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:15 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber  
java.lang.NullPointerException: null  
	at net.runelite.client.plugins.zulrah.ZulrahPlugin.onGameTick(ZulrahPlugin.java:170)  
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:72)  
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:218)  
	at net.runelite.client.callback.Hooks.clientMainLoop(Hooks.java:155)  
	at client.methodDraw(client.java:1340)  
	at client.ab(client.java)  
	at ba.ar(ba.java:419)  
	at ba.run(ba.java:373)  
	at java.lang.Thread.run(Unknown Source)  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
2019-06-13 12:09:16 [Client] DEBUG n.r.c.p.z.overlays.ZulrahOverlay - Current phase is NULL  
```

**Comment by ILLuMiNaTe7** [comment]
[client.log](https://github.com/runelite-extended/runelite/files/3286354/client.log)
Since the formatting doesn't work for code here is a file with the log.

**Comment by f0rmatme** [comment]
fixed
