### ISSUE TITLE
NPE with slayer plugin

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#804]
Running latest build, logged into client and my debug was spammed with this

```
2019-06-29 13:20:50 [Client] WARN  net.runelite.client.callback.Hooks - Error during overlay rendering
java.lang.NullPointerException: null
	at net.runelite.client.plugins.slayer.SlayerPlugin.isSuperior(SlayerPlugin.java:732)
	at net.runelite.client.plugins.slayer.TargetClickboxOverlay.render(TargetClickboxOverlay.java:80)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:461)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:227)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:395)
	at em.az(em.java:304)
	at ad.gf(ad.java:4903)
	at az.ir(az.java:9676)
	at bv.iz(bv.java:9565)
	at client.gs(client.java:4587)
	at client.ab(client.java:1690)
	at ba.ar(ba.java:419)
	at ba.run(ba.java:373)
	at java.lang.Thread.run(Thread.java:748)
```

Reloaded client and the same output is spammed, this hides any InfoBoxes that are turned on (stat boosts, slayer counter)

**Comment by Ganom** [comment]
Should be fixed in https://github.com/runelite-extended/runelite/pull/810
