### ISSUE TITLE
AssertionError with ItemManager/StonedLootTracker

### ISSUE THREAD

**Issue by SRLJustin** [runelite-extended/runelite#827]
When clicking on an NPC in the StonedLootTracker that you havn't killed before, the side panel will crash and the following error is thrown:

```
2019-06-30 13:54:19 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.AssertionError: getItemDefinition must be called on client thread
	at net.runelite.client.game.ItemManager.getItemDefinition(ItemManager.java:493)
	at net.runelite.client.game.ItemManager.getAlchValue(ItemManager.java:441)
	at net.runelite.client.plugins.stonedloottracker.ui.UniqueItemPanel.<init>(UniqueItemPanel.java:92)
	at net.runelite.client.plugins.stonedloottracker.ui.LootPanel.lambda$createPanel$2(LootPanel.java:161)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at net.runelite.client.plugins.stonedloottracker.ui.LootPanel.createPanel(LootPanel.java:159)
	at net.runelite.client.plugins.stonedloottracker.ui.LootPanel.<init>(LootPanel.java:80)
	at net.runelite.client.plugins.stonedloottracker.ui.LootTrackerPanel.showLootView(LootTrackerPanel.java:150)
	at net.runelite.client.plugins.stonedloottracker.ui.SelectionPanel$2.lambda$mouseClicked$0(SelectionPanel.java:194)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)2019-06-30 13:54:19 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.AssertionError: getItemDefinition must be called on client thread
	at net.runelite.client.game.ItemManager.getItemDefinition(ItemManager.java:493)
	at net.runelite.client.game.ItemManager.getAlchValue(ItemManager.java:441)
	at net.runelite.client.plugins.stonedloottracker.ui.UniqueItemPanel.<init>(UniqueItemPanel.java:92)
	at net.runelite.client.plugins.stonedloottracker.ui.LootPanel.lambda$createPanel$2(LootPanel.java:161)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at net.runelite.client.plugins.stonedloottracker.ui.LootPanel.createPanel(LootPanel.java:159)
	at net.runelite.client.plugins.stonedloottracker.ui.LootPanel.<init>(LootPanel.java:80)
	at net.runelite.client.plugins.stonedloottracker.ui.LootTrackerPanel.showLootView(LootTrackerPanel.java:150)
	at net.runelite.client.plugins.stonedloottracker.ui.SelectionPanel$2.lambda$mouseClicked$0(SelectionPanel.java:194)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```
The side panel will no longer respond or show any icons

![image](https://user-images.githubusercontent.com/1625140/60392056-248d5d80-9b3f-11e9-9cd4-de14f9532a20.png)

**Comment by Owain94** [comment]
The same happens in the RL loot tracker when you run the client with assertions enabled right?
