### ISSUE TITLE
RL+ won't open but RL Does.

### ISSUE THREAD

**Issue by SlothTheHobo** [runelite-extended/runelite#936]
Here is the issue I get when launching RL+

2019-07-08 08:28:10 [main] INFO  net.runelite.launcher.Launcher - Setting hardware acceleration to DIRECTDRAW
2019-07-08 08:28:11 [main] ERROR net.runelite.launcher.Launcher - error fetching bootstrap
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:704)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
	at net.runelite.launcher.Launcher.getBootstrap(Launcher.java:273)
	at net.runelite.launcher.Launcher.main(Launcher.java:167)

**Comment by Kyleeld** [comment]
Allow rl+ through your firewall or turn it off, the connection outbound is being blocked

**Comment by SlothTheHobo** [comment]
> Allow rl+ through your firewall or turn it off, the connection outbound is being blocked

Now it's sitting @ 0%.

**Comment by f0rmatme** [comment]
It looks like you cant access internet, that is not something we can affect
